### ISSUE TITLE
Front-end posting breaks when pretty permalinks are disabled

### ISSUE THREAD

**Issue by williamsba** [WebDevStudios/CollabPress#112]
If you do any type of content actions on the front-end (create a project, update a project, etc) and pretty permalinks are disabled, the action will happen but the page refreshes to the home screen.  It appears to lose the page/post ID in the querystring which is causing the issue.

**Comment by scottbasgaard** [comment]
@williamsba this fixed now? I can't replicate.

**Comment by williamsba** [comment]
I titled this wrong, it happens when pretty permalinks are **disabled**.  This is still happening and seems related to the cp_get_project_permalink() function in functions.php.
